version: "3.8"

services:
  messages_api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      DATABASE_HOST: messages_api_db
      DATABASE_USERNAME: user
      DATABASE_PASSWORD: password
    depends_on:
      - messages_api_db

  messages_api_db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: messages_api_development
    ports:
      - "5432:5432"
    volumes:
      - messages_api_db_data:/var/lib/postgresql/data

volumes:
  messages_api_db_data:
